@apiUrl = http://localhost:3000/api
# Obter a lista de colaboradores
GET {{apiUrl}}/colaboradores
Content-Type: application/json
###

# Inserir novo colaborador
POST {{apiUrl}}/colaboradores
Content-Type: application/json

{
 "nome": "Eduardo Bonamigo Bianchetti", "email": "185961@upf.br",
 "senha": "123"
}
###

# Alterar colaborador
PUT {{apiUrl}}/colaboradores
Content-Type: application/json

{
 "_id": "62313ad4979154f743b60f12",
 "nome": "Jaqson alterado",
 "email": "jaqson@teste.com",
 "senha": "321"
}

###
# Excluir um colaborador
DELETE {{apiUrl}}/colaboradores/623a58372ddf422aed73b525
Content-Type: application/json
###

# Obter pelo id de colaborador
GET {{apiUrl}}/colaboradores/623a58372ddf422aed73b525
Content-Type: application/json

###
# Obter colaborador filtrando
GET {{apiUrl}}/colaboradores/filtro/admin
Content-Type: application/json
###