@apiUrl = http://localhost:3000/api
# Obter a lista de requisicoes
GET {{apiUrl}}/requisicoes
Content-Type: application/json
###

# Inserir nova requisicao
POST {{apiUrl}}/requisicoes
Content-Type: application/json

{
 "titulo": "Requisição de Conserto", "descricao": "Necessito de Conserto para meu veículo",
 "status": "Recebido", "prazoAtendimento": "2022-04-20", 
 "tipoRequisicao": "6240a99cbb1b289857f69cbf", "solicitante": "6240a987bb1b289857f69cbc"
}
###

# Alterar requisicao
PUT {{apiUrl}}/requisicoes
Content-Type: application/json

{
 "_id": "6240aa80bb1b289857f69cd4",
 "titulo": "Requisição de Conserto", 
 "descricao": "Necessito de Conserto para meu veículo",
 "status": "Em andamento", 
 "prazoAtendimento": "2022-04-20" 
}

###
# Excluir uma requisicao
DELETE {{apiUrl}}/requisicoes/6240aa7bbb1b289857f69cd2
Content-Type: application/json
###

# Obter pelo id de requisicao
GET {{apiUrl}}/requisicoes/6240aa80bb1b289857f69cd4
Content-Type: application/json

###
# Obter requisicao filtrando
GET {{apiUrl}}/requisicoes/filtro/Andamento
Content-Type: application/json
###