@apiUrl = http://localhost:3000/api
# Obter a lista de solicitantes
GET {{apiUrl}}/solicitantes
Content-Type: application/json
###

# Inserir novo solicitante
POST {{apiUrl}}/solicitantes
Content-Type: application/json

{
 "nome": "Fulano", "email": "fulano@outlook.com",
 "senha": "123"
}
###

# Alterar solicitante
PUT {{apiUrl}}/solicitantes
Content-Type: application/json

{
 "_id": "624389e7bd602ec54525b3d7",
 "nome": "Fulano",
 "email": "fulano@upf.br",
 "senha": "123"
}

###
# Excluir um solicitante
DELETE {{apiUrl}}/solicitantes/623a669c493851463454da9f
Content-Type: application/json
###

# Obter pelo id de solicitante
GET {{apiUrl}}/solicitantes/623a669c493851463454da9f
Content-Type: application/json

###
# Obter solicitante filtrando
GET {{apiUrl}}/solicitantes/filtro/fulano
Content-Type: application/json
###

# Autenticação de colaborador
POST {{apiUrl}}/solicitantes/login
Content-Type: application/json

{
 "email": "fulano@upf.br",
 "senha": "123"
}
###